// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_community_occ_fit
Rcpp::List cpp_community_occ_fit(Rcpp::IntegerMatrix y_r, Rcpp::NumericMatrix X_occ_r, Rcpp::NumericMatrix X_det_r, Rcpp::IntegerVector species_group_r, int n_species, double sigma_beta, double sigma_re_scale, int n_iter, int n_warmup, int max_treedepth, double adapt_delta, int seed, bool verbose);
RcppExport SEXP _tulpaOcc_cpp_community_occ_fit(SEXP y_rSEXP, SEXP X_occ_rSEXP, SEXP X_det_rSEXP, SEXP species_group_rSEXP, SEXP n_speciesSEXP, SEXP sigma_betaSEXP, SEXP sigma_re_scaleSEXP, SEXP n_iterSEXP, SEXP n_warmupSEXP, SEXP max_treedepthSEXP, SEXP adapt_deltaSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type y_r(y_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_occ_r(X_occ_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_det_r(X_det_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type species_group_r(species_group_rSEXP);
    Rcpp::traits::input_parameter< int >::type n_species(n_speciesSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_beta(sigma_betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_re_scale(sigma_re_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_warmup(n_warmupSEXP);
    Rcpp::traits::input_parameter< int >::type max_treedepth(max_treedepthSEXP);
    Rcpp::traits::input_parameter< double >::type adapt_delta(adapt_deltaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_community_occ_fit(y_r, X_occ_r, X_det_r, species_group_r, n_species, sigma_beta, sigma_re_scale, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dyn_occ_fit
Rcpp::List cpp_dyn_occ_fit(Rcpp::IntegerVector y_flat_r, Rcpp::IntegerVector n_visits_r, Rcpp::LogicalVector any_detected_r, Rcpp::NumericMatrix X_occ_r, Rcpp::NumericMatrix X_det_r, Rcpp::NumericMatrix X_col_r, Rcpp::NumericMatrix X_ext_r, int n_sites, int n_seasons, int max_visits, double sigma_beta, int n_iter, int n_warmup, int max_treedepth, double adapt_delta, int seed, bool verbose);
RcppExport SEXP _tulpaOcc_cpp_dyn_occ_fit(SEXP y_flat_rSEXP, SEXP n_visits_rSEXP, SEXP any_detected_rSEXP, SEXP X_occ_rSEXP, SEXP X_det_rSEXP, SEXP X_col_rSEXP, SEXP X_ext_rSEXP, SEXP n_sitesSEXP, SEXP n_seasonsSEXP, SEXP max_visitsSEXP, SEXP sigma_betaSEXP, SEXP n_iterSEXP, SEXP n_warmupSEXP, SEXP max_treedepthSEXP, SEXP adapt_deltaSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y_flat_r(y_flat_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_visits_r(n_visits_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type any_detected_r(any_detected_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_occ_r(X_occ_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_det_r(X_det_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_col_r(X_col_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_ext_r(X_ext_rSEXP);
    Rcpp::traits::input_parameter< int >::type n_sites(n_sitesSEXP);
    Rcpp::traits::input_parameter< int >::type n_seasons(n_seasonsSEXP);
    Rcpp::traits::input_parameter< int >::type max_visits(max_visitsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_beta(sigma_betaSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_warmup(n_warmupSEXP);
    Rcpp::traits::input_parameter< int >::type max_treedepth(max_treedepthSEXP);
    Rcpp::traits::input_parameter< double >::type adapt_delta(adapt_deltaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dyn_occ_fit(y_flat_r, n_visits_r, any_detected_r, X_occ_r, X_det_r, X_col_r, X_ext_r, n_sites, n_seasons, max_visits, sigma_beta, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_occ_fit
Rcpp::List cpp_occ_fit(Rcpp::IntegerMatrix y_r, Rcpp::NumericMatrix X_occ_r, Rcpp::NumericMatrix X_det_r, Rcpp::Nullable<Rcpp::NumericMatrix> X_det_visit_r, Rcpp::Nullable<Rcpp::List> spatial_params_r, double sigma_beta, int n_iter, int n_warmup, int max_treedepth, double adapt_delta, int seed, bool verbose);
RcppExport SEXP _tulpaOcc_cpp_occ_fit(SEXP y_rSEXP, SEXP X_occ_rSEXP, SEXP X_det_rSEXP, SEXP X_det_visit_rSEXP, SEXP spatial_params_rSEXP, SEXP sigma_betaSEXP, SEXP n_iterSEXP, SEXP n_warmupSEXP, SEXP max_treedepthSEXP, SEXP adapt_deltaSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type y_r(y_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_occ_r(X_occ_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_det_r(X_det_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type X_det_visit_r(X_det_visit_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type spatial_params_r(spatial_params_rSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_beta(sigma_betaSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_warmup(n_warmupSEXP);
    Rcpp::traits::input_parameter< int >::type max_treedepth(max_treedepthSEXP);
    Rcpp::traits::input_parameter< double >::type adapt_delta(adapt_deltaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_occ_fit(y_r, X_occ_r, X_det_r, X_det_visit_r, spatial_params_r, sigma_beta, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tulpaOcc_cpp_community_occ_fit", (DL_FUNC) &_tulpaOcc_cpp_community_occ_fit, 13},
    {"_tulpaOcc_cpp_dyn_occ_fit", (DL_FUNC) &_tulpaOcc_cpp_dyn_occ_fit, 17},
    {"_tulpaOcc_cpp_occ_fit", (DL_FUNC) &_tulpaOcc_cpp_occ_fit, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_tulpaOcc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
