// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_register_occu_cover_lognormal_coupling
void cpp_register_occu_cover_lognormal_coupling();
RcppExport SEXP _tulpaObs_cpp_register_occu_cover_lognormal_coupling() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_register_occu_cover_lognormal_coupling();
    return R_NilValue;
END_RCPP
}
// cpp_register_occu_cover_beta_coupling
void cpp_register_occu_cover_beta_coupling();
RcppExport SEXP _tulpaObs_cpp_register_occu_cover_beta_coupling() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_register_occu_cover_beta_coupling();
    return R_NilValue;
END_RCPP
}
// cpp_eval_occu_cover_lognormal_cell
Rcpp::List cpp_eval_occu_cover_lognormal_cell(double eta_psi, Rcpp::NumericVector eta_p, Rcpp::NumericVector eta_pos, Rcpp::IntegerVector y_det, Rcpp::NumericVector y_pos, double sigma_pos, std::string curvature);
RcppExport SEXP _tulpaObs_cpp_eval_occu_cover_lognormal_cell(SEXP eta_psiSEXP, SEXP eta_pSEXP, SEXP eta_posSEXP, SEXP y_detSEXP, SEXP y_posSEXP, SEXP sigma_posSEXP, SEXP curvatureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta_psi(eta_psiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_p(eta_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_pos(eta_posSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y_det(y_detSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_pos(y_posSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_pos(sigma_posSEXP);
    Rcpp::traits::input_parameter< std::string >::type curvature(curvatureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_eval_occu_cover_lognormal_cell(eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature));
    return rcpp_result_gen;
END_RCPP
}
// cpp_eval_occu_cover_beta_cell
Rcpp::List cpp_eval_occu_cover_beta_cell(double eta_psi, Rcpp::NumericVector eta_p, Rcpp::NumericVector eta_pos, Rcpp::IntegerVector y_det, Rcpp::NumericVector y_pos, double phi_pos, std::string curvature);
RcppExport SEXP _tulpaObs_cpp_eval_occu_cover_beta_cell(SEXP eta_psiSEXP, SEXP eta_pSEXP, SEXP eta_posSEXP, SEXP y_detSEXP, SEXP y_posSEXP, SEXP phi_posSEXP, SEXP curvatureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta_psi(eta_psiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_p(eta_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_pos(eta_posSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y_det(y_detSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_pos(y_posSEXP);
    Rcpp::traits::input_parameter< double >::type phi_pos(phi_posSEXP);
    Rcpp::traits::input_parameter< std::string >::type curvature(curvatureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_eval_occu_cover_beta_cell(eta_psi, eta_p, eta_pos, y_det, y_pos, phi_pos, curvature));
    return rcpp_result_gen;
END_RCPP
}
// cpp_register_occu_multiscale_cover_coupling
std::string cpp_register_occu_multiscale_cover_coupling(std::string positive, Rcpp::IntegerVector n_plots_per_cell, Rcpp::IntegerVector plot_sizes_flat);
RcppExport SEXP _tulpaObs_cpp_register_occu_multiscale_cover_coupling(SEXP positiveSEXP, SEXP n_plots_per_cellSEXP, SEXP plot_sizes_flatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type positive(positiveSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_plots_per_cell(n_plots_per_cellSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type plot_sizes_flat(plot_sizes_flatSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_register_occu_multiscale_cover_coupling(positive, n_plots_per_cell, plot_sizes_flat));
    return rcpp_result_gen;
END_RCPP
}
// cpp_eval_occu_multiscale_cover_lognormal_cell
Rcpp::List cpp_eval_occu_multiscale_cover_lognormal_cell(double eta_psi, Rcpp::NumericVector eta_theta, Rcpp::NumericVector eta_p, Rcpp::NumericVector eta_pos, Rcpp::IntegerVector y_det, Rcpp::NumericVector y_pos, Rcpp::IntegerVector plot_sizes, double sigma_pos, std::string curvature);
RcppExport SEXP _tulpaObs_cpp_eval_occu_multiscale_cover_lognormal_cell(SEXP eta_psiSEXP, SEXP eta_thetaSEXP, SEXP eta_pSEXP, SEXP eta_posSEXP, SEXP y_detSEXP, SEXP y_posSEXP, SEXP plot_sizesSEXP, SEXP sigma_posSEXP, SEXP curvatureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta_psi(eta_psiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_theta(eta_thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_p(eta_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_pos(eta_posSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y_det(y_detSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_pos(y_posSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type plot_sizes(plot_sizesSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_pos(sigma_posSEXP);
    Rcpp::traits::input_parameter< std::string >::type curvature(curvatureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_eval_occu_multiscale_cover_lognormal_cell(eta_psi, eta_theta, eta_p, eta_pos, y_det, y_pos, plot_sizes, sigma_pos, curvature));
    return rcpp_result_gen;
END_RCPP
}
// cpp_eval_occu_multiscale_cover_beta_cell
Rcpp::List cpp_eval_occu_multiscale_cover_beta_cell(double eta_psi, Rcpp::NumericVector eta_theta, Rcpp::NumericVector eta_p, Rcpp::NumericVector eta_pos, Rcpp::IntegerVector y_det, Rcpp::NumericVector y_pos, Rcpp::IntegerVector plot_sizes, double phi_pos, std::string curvature);
RcppExport SEXP _tulpaObs_cpp_eval_occu_multiscale_cover_beta_cell(SEXP eta_psiSEXP, SEXP eta_thetaSEXP, SEXP eta_pSEXP, SEXP eta_posSEXP, SEXP y_detSEXP, SEXP y_posSEXP, SEXP plot_sizesSEXP, SEXP phi_posSEXP, SEXP curvatureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eta_psi(eta_psiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_theta(eta_thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_p(eta_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_pos(eta_posSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y_det(y_detSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_pos(y_posSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type plot_sizes(plot_sizesSEXP);
    Rcpp::traits::input_parameter< double >::type phi_pos(phi_posSEXP);
    Rcpp::traits::input_parameter< std::string >::type curvature(curvatureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_eval_occu_multiscale_cover_beta_cell(eta_psi, eta_theta, eta_p, eta_pos, y_det, y_pos, plot_sizes, phi_pos, curvature));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_community_em
List cpp_nmix_community_em(SEXP oracle, NumericVector mu_init, NumericMatrix Sigma_lambda_init, NumericMatrix Sigma_p_init, int max_iter, double tol, int inner_max, double inner_tol, double sigma_beta, bool verbose);
RcppExport SEXP _tulpaObs_cpp_nmix_community_em(SEXP oracleSEXP, SEXP mu_initSEXP, SEXP Sigma_lambda_initSEXP, SEXP Sigma_p_initSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP inner_maxSEXP, SEXP inner_tolSEXP, SEXP sigma_betaSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type oracle(oracleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma_lambda_init(Sigma_lambda_initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma_p_init(Sigma_p_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type inner_max(inner_maxSEXP);
    Rcpp::traits::input_parameter< double >::type inner_tol(inner_tolSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_beta(sigma_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_community_em(oracle, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter, tol, inner_max, inner_tol, sigma_beta, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_community_field_solve
Rcpp::List cpp_nmix_community_field_solve(Rcpp::IntegerVector y, Rcpp::IntegerVector site_idx, Rcpp::IntegerVector species_idx, Rcpp::NumericMatrix X_lambda, Rcpp::NumericMatrix X_p, Rcpp::NumericMatrix coef_lambda, Rcpp::NumericMatrix coef_p, Rcpp::IntegerVector map_site_to_unit_R, Rcpp::IntegerVector adj_row_ptr, Rcpp::IntegerVector adj_col_idx, Rcpp::IntegerVector n_neighbors, int n_spatial, double tau, double rho, double log_det_Q_rho, Rcpp::NumericVector z_init, int K_max, int max_iter, double tol, bool verbose);
RcppExport SEXP _tulpaObs_cpp_nmix_community_field_solve(SEXP ySEXP, SEXP site_idxSEXP, SEXP species_idxSEXP, SEXP X_lambdaSEXP, SEXP X_pSEXP, SEXP coef_lambdaSEXP, SEXP coef_pSEXP, SEXP map_site_to_unit_RSEXP, SEXP adj_row_ptrSEXP, SEXP adj_col_idxSEXP, SEXP n_neighborsSEXP, SEXP n_spatialSEXP, SEXP tauSEXP, SEXP rhoSEXP, SEXP log_det_Q_rhoSEXP, SEXP z_initSEXP, SEXP K_maxSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_idx(site_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda(X_lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_p(X_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type coef_lambda(coef_lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type coef_p(coef_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type map_site_to_unit_R(map_site_to_unit_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_row_ptr(adj_row_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_col_idx(adj_col_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type n_spatial(n_spatialSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type log_det_Q_rho(log_det_Q_rhoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type z_init(z_initSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_community_field_solve(y, site_idx, species_idx, X_lambda, X_p, coef_lambda, coef_p, map_site_to_unit_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau, rho, log_det_Q_rho, z_init, K_max, max_iter, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_community_oracle
SEXP cpp_nmix_community_oracle(Rcpp::IntegerVector y, Rcpp::IntegerVector site_idx, Rcpp::IntegerVector species_idx, Rcpp::NumericMatrix X_lambda, Rcpp::NumericMatrix X_p, int n_sites, int n_species, int K_max, bool nb);
RcppExport SEXP _tulpaObs_cpp_nmix_community_oracle(SEXP ySEXP, SEXP site_idxSEXP, SEXP species_idxSEXP, SEXP X_lambdaSEXP, SEXP X_pSEXP, SEXP n_sitesSEXP, SEXP n_speciesSEXP, SEXP K_maxSEXP, SEXP nbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_idx(site_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda(X_lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_p(X_pSEXP);
    Rcpp::traits::input_parameter< int >::type n_sites(n_sitesSEXP);
    Rcpp::traits::input_parameter< int >::type n_species(n_speciesSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type nb(nbSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_community_oracle(y, site_idx, species_idx, X_lambda, X_p, n_sites, n_species, K_max, nb));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_community_spatial_icar
Rcpp::List cpp_nmix_community_spatial_icar(SEXP oracle, Rcpp::IntegerVector map_site_to_unit_R, Rcpp::NumericMatrix X_lambda_R, Rcpp::IntegerVector adj_row_ptr, Rcpp::IntegerVector adj_col_idx, Rcpp::IntegerVector n_neighbors, int n_spatial, Rcpp::NumericVector tau_grid, Rcpp::NumericVector r_grid, Rcpp::NumericVector mu_init, Rcpp::NumericMatrix Sigma_lambda_init, Rcpp::NumericMatrix Sigma_p_init, int max_iter_em, double tol_em, int inner_max, double inner_tol, double sigma_beta, bool verbose, bool progress, int progress_every, double progress_throttle, std::string progress_file);
RcppExport SEXP _tulpaObs_cpp_nmix_community_spatial_icar(SEXP oracleSEXP, SEXP map_site_to_unit_RSEXP, SEXP X_lambda_RSEXP, SEXP adj_row_ptrSEXP, SEXP adj_col_idxSEXP, SEXP n_neighborsSEXP, SEXP n_spatialSEXP, SEXP tau_gridSEXP, SEXP r_gridSEXP, SEXP mu_initSEXP, SEXP Sigma_lambda_initSEXP, SEXP Sigma_p_initSEXP, SEXP max_iter_emSEXP, SEXP tol_emSEXP, SEXP inner_maxSEXP, SEXP inner_tolSEXP, SEXP sigma_betaSEXP, SEXP verboseSEXP, SEXP progressSEXP, SEXP progress_everySEXP, SEXP progress_throttleSEXP, SEXP progress_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type oracle(oracleSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type map_site_to_unit_R(map_site_to_unit_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda_R(X_lambda_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_row_ptr(adj_row_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_col_idx(adj_col_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type n_spatial(n_spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tau_grid(tau_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r_grid(r_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Sigma_lambda_init(Sigma_lambda_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Sigma_p_init(Sigma_p_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_em(max_iter_emSEXP);
    Rcpp::traits::input_parameter< double >::type tol_em(tol_emSEXP);
    Rcpp::traits::input_parameter< int >::type inner_max(inner_maxSEXP);
    Rcpp::traits::input_parameter< double >::type inner_tol(inner_tolSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_beta(sigma_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_every(progress_everySEXP);
    Rcpp::traits::input_parameter< double >::type progress_throttle(progress_throttleSEXP);
    Rcpp::traits::input_parameter< std::string >::type progress_file(progress_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_community_spatial_icar(oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_community_spatial_car_proper
Rcpp::List cpp_nmix_community_spatial_car_proper(SEXP oracle, Rcpp::IntegerVector map_site_to_unit_R, Rcpp::NumericMatrix X_lambda_R, Rcpp::IntegerVector adj_row_ptr, Rcpp::IntegerVector adj_col_idx, Rcpp::IntegerVector n_neighbors, int n_spatial, Rcpp::NumericVector tau_grid, Rcpp::NumericVector rho_grid, Rcpp::NumericVector log_det_Q_rho, Rcpp::NumericVector r_grid, Rcpp::NumericVector mu_init, Rcpp::NumericMatrix Sigma_lambda_init, Rcpp::NumericMatrix Sigma_p_init, int max_iter_em, double tol_em, int inner_max, double inner_tol, double sigma_beta, bool verbose, bool progress, int progress_every, double progress_throttle, std::string progress_file);
RcppExport SEXP _tulpaObs_cpp_nmix_community_spatial_car_proper(SEXP oracleSEXP, SEXP map_site_to_unit_RSEXP, SEXP X_lambda_RSEXP, SEXP adj_row_ptrSEXP, SEXP adj_col_idxSEXP, SEXP n_neighborsSEXP, SEXP n_spatialSEXP, SEXP tau_gridSEXP, SEXP rho_gridSEXP, SEXP log_det_Q_rhoSEXP, SEXP r_gridSEXP, SEXP mu_initSEXP, SEXP Sigma_lambda_initSEXP, SEXP Sigma_p_initSEXP, SEXP max_iter_emSEXP, SEXP tol_emSEXP, SEXP inner_maxSEXP, SEXP inner_tolSEXP, SEXP sigma_betaSEXP, SEXP verboseSEXP, SEXP progressSEXP, SEXP progress_everySEXP, SEXP progress_throttleSEXP, SEXP progress_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type oracle(oracleSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type map_site_to_unit_R(map_site_to_unit_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda_R(X_lambda_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_row_ptr(adj_row_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_col_idx(adj_col_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type n_spatial(n_spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tau_grid(tau_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rho_grid(rho_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type log_det_Q_rho(log_det_Q_rhoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r_grid(r_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Sigma_lambda_init(Sigma_lambda_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Sigma_p_init(Sigma_p_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_em(max_iter_emSEXP);
    Rcpp::traits::input_parameter< double >::type tol_em(tol_emSEXP);
    Rcpp::traits::input_parameter< int >::type inner_max(inner_maxSEXP);
    Rcpp::traits::input_parameter< double >::type inner_tol(inner_tolSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_beta(sigma_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_every(progress_everySEXP);
    Rcpp::traits::input_parameter< double >::type progress_throttle(progress_throttleSEXP);
    Rcpp::traits::input_parameter< std::string >::type progress_file(progress_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_community_spatial_car_proper(oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, log_det_Q_rho, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_community_spatial_bym2
Rcpp::List cpp_nmix_community_spatial_bym2(SEXP oracle, Rcpp::IntegerVector map_site_to_unit_R, Rcpp::NumericMatrix X_lambda_R, Rcpp::IntegerVector adj_row_ptr, Rcpp::IntegerVector adj_col_idx, Rcpp::IntegerVector n_neighbors, int n_spatial, Rcpp::NumericVector sigma_grid, Rcpp::NumericVector rho_grid, double scale_factor, Rcpp::NumericVector r_grid, Rcpp::NumericVector mu_init, Rcpp::NumericMatrix Sigma_lambda_init, Rcpp::NumericMatrix Sigma_p_init, int max_iter_em, double tol_em, int inner_max, double inner_tol, double sigma_beta, bool verbose, bool progress, int progress_every, double progress_throttle, std::string progress_file);
RcppExport SEXP _tulpaObs_cpp_nmix_community_spatial_bym2(SEXP oracleSEXP, SEXP map_site_to_unit_RSEXP, SEXP X_lambda_RSEXP, SEXP adj_row_ptrSEXP, SEXP adj_col_idxSEXP, SEXP n_neighborsSEXP, SEXP n_spatialSEXP, SEXP sigma_gridSEXP, SEXP rho_gridSEXP, SEXP scale_factorSEXP, SEXP r_gridSEXP, SEXP mu_initSEXP, SEXP Sigma_lambda_initSEXP, SEXP Sigma_p_initSEXP, SEXP max_iter_emSEXP, SEXP tol_emSEXP, SEXP inner_maxSEXP, SEXP inner_tolSEXP, SEXP sigma_betaSEXP, SEXP verboseSEXP, SEXP progressSEXP, SEXP progress_everySEXP, SEXP progress_throttleSEXP, SEXP progress_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type oracle(oracleSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type map_site_to_unit_R(map_site_to_unit_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda_R(X_lambda_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_row_ptr(adj_row_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_col_idx(adj_col_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type n_spatial(n_spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma_grid(sigma_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rho_grid(rho_gridSEXP);
    Rcpp::traits::input_parameter< double >::type scale_factor(scale_factorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r_grid(r_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Sigma_lambda_init(Sigma_lambda_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Sigma_p_init(Sigma_p_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_em(max_iter_emSEXP);
    Rcpp::traits::input_parameter< double >::type tol_em(tol_emSEXP);
    Rcpp::traits::input_parameter< int >::type inner_max(inner_maxSEXP);
    Rcpp::traits::input_parameter< double >::type inner_tol(inner_tolSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_beta(sigma_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_every(progress_everySEXP);
    Rcpp::traits::input_parameter< double >::type progress_throttle(progress_throttleSEXP);
    Rcpp::traits::input_parameter< std::string >::type progress_file(progress_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_community_spatial_bym2(oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, scale_factor, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_community_spatial_spde
Rcpp::List cpp_nmix_community_spatial_spde(SEXP oracle, Rcpp::NumericMatrix X_lambda_R, Rcpp::NumericMatrix A_R, Rcpp::List Q_list, Rcpp::NumericVector log_det_Q, Rcpp::NumericMatrix theta_grid_R, Rcpp::NumericVector r_grid, Rcpp::NumericVector mu_init, Rcpp::NumericMatrix Sigma_lambda_init, Rcpp::NumericMatrix Sigma_p_init, int max_iter_em, double tol_em, int inner_max, double inner_tol, double sigma_beta, bool verbose, bool progress, int progress_every, double progress_throttle, std::string progress_file);
RcppExport SEXP _tulpaObs_cpp_nmix_community_spatial_spde(SEXP oracleSEXP, SEXP X_lambda_RSEXP, SEXP A_RSEXP, SEXP Q_listSEXP, SEXP log_det_QSEXP, SEXP theta_grid_RSEXP, SEXP r_gridSEXP, SEXP mu_initSEXP, SEXP Sigma_lambda_initSEXP, SEXP Sigma_p_initSEXP, SEXP max_iter_emSEXP, SEXP tol_emSEXP, SEXP inner_maxSEXP, SEXP inner_tolSEXP, SEXP sigma_betaSEXP, SEXP verboseSEXP, SEXP progressSEXP, SEXP progress_everySEXP, SEXP progress_throttleSEXP, SEXP progress_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type oracle(oracleSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda_R(X_lambda_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A_R(A_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Q_list(Q_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type log_det_Q(log_det_QSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type theta_grid_R(theta_grid_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r_grid(r_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Sigma_lambda_init(Sigma_lambda_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Sigma_p_init(Sigma_p_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_em(max_iter_emSEXP);
    Rcpp::traits::input_parameter< double >::type tol_em(tol_emSEXP);
    Rcpp::traits::input_parameter< int >::type inner_max(inner_maxSEXP);
    Rcpp::traits::input_parameter< double >::type inner_tol(inner_tolSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_beta(sigma_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_every(progress_everySEXP);
    Rcpp::traits::input_parameter< double >::type progress_throttle(progress_throttleSEXP);
    Rcpp::traits::input_parameter< std::string >::type progress_file(progress_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_community_spatial_spde(oracle, X_lambda_R, A_R, Q_list, log_det_Q, theta_grid_R, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_spatial_community_oracle
SEXP cpp_nmix_spatial_community_oracle(Rcpp::IntegerVector y, Rcpp::IntegerVector site_idx, Rcpp::IntegerVector species_idx, Rcpp::NumericMatrix X_lambda, Rcpp::NumericMatrix X_p, int n_sites, int n_species, int K_max);
RcppExport SEXP _tulpaObs_cpp_nmix_spatial_community_oracle(SEXP ySEXP, SEXP site_idxSEXP, SEXP species_idxSEXP, SEXP X_lambdaSEXP, SEXP X_pSEXP, SEXP n_sitesSEXP, SEXP n_speciesSEXP, SEXP K_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_idx(site_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda(X_lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_p(X_pSEXP);
    Rcpp::traits::input_parameter< int >::type n_sites(n_sitesSEXP);
    Rcpp::traits::input_parameter< int >::type n_species(n_speciesSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_spatial_community_oracle(y, site_idx, species_idx, X_lambda, X_p, n_sites, n_species, K_max));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_spatial_community_set_offset
void cpp_nmix_spatial_community_set_offset(SEXP oracle_ptr, Rcpp::NumericVector z);
RcppExport SEXP _tulpaObs_cpp_nmix_spatial_community_set_offset(SEXP oracle_ptrSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type oracle_ptr(oracle_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type z(zSEXP);
    cpp_nmix_spatial_community_set_offset(oracle_ptr, z);
    return R_NilValue;
END_RCPP
}
// cpp_nmix_laplace_fixed
Rcpp::List cpp_nmix_laplace_fixed(Rcpp::IntegerVector y, Rcpp::IntegerVector site_idx, Rcpp::NumericMatrix X_lambda_R, Rcpp::NumericMatrix X_p_R, Rcpp::NumericVector beta_lambda_init, Rcpp::NumericVector beta_p_init, int K_max, int max_iter, double tol, bool verbose, bool nb, double log_r_init, double theta_max);
RcppExport SEXP _tulpaObs_cpp_nmix_laplace_fixed(SEXP ySEXP, SEXP site_idxSEXP, SEXP X_lambda_RSEXP, SEXP X_p_RSEXP, SEXP beta_lambda_initSEXP, SEXP beta_p_initSEXP, SEXP K_maxSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP nbSEXP, SEXP log_r_initSEXP, SEXP theta_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_idx(site_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda_R(X_lambda_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_p_R(X_p_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_lambda_init(beta_lambda_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_p_init(beta_p_initSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type log_r_init(log_r_initSEXP);
    Rcpp::traits::input_parameter< double >::type theta_max(theta_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_laplace_fixed(y, site_idx, X_lambda_R, X_p_R, beta_lambda_init, beta_p_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_total_log_lik
Rcpp::List cpp_nmix_total_log_lik(Rcpp::IntegerVector y, Rcpp::IntegerVector site_idx, Rcpp::NumericVector eta_p, Rcpp::NumericVector eta_lambda, int K_max, double r);
RcppExport SEXP _tulpaObs_cpp_nmix_total_log_lik(SEXP ySEXP, SEXP site_idxSEXP, SEXP eta_pSEXP, SEXP eta_lambdaSEXP, SEXP K_maxSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_idx(site_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_p(eta_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_lambda(eta_lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_total_log_lik(y, site_idx, eta_p, eta_lambda, K_max, r));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nmix_grouped_oracle
SEXP cpp_nmix_grouped_oracle(int arm, Rcpp::IntegerVector y, Rcpp::IntegerVector site_idx, Rcpp::NumericMatrix X_lambda, Rcpp::NumericMatrix X_p, Rcpp::NumericMatrix Z_site, Rcpp::IntegerVector site_group, int n_sites, int n_groups, int K_max, bool nb);
RcppExport SEXP _tulpaObs_cpp_nmix_grouped_oracle(SEXP armSEXP, SEXP ySEXP, SEXP site_idxSEXP, SEXP X_lambdaSEXP, SEXP X_pSEXP, SEXP Z_siteSEXP, SEXP site_groupSEXP, SEXP n_sitesSEXP, SEXP n_groupsSEXP, SEXP K_maxSEXP, SEXP nbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type arm(armSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_idx(site_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda(X_lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_p(X_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_group(site_groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_sites(n_sitesSEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type nb(nbSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nmix_grouped_oracle(arm, y, site_idx, X_lambda, X_p, Z_site, site_group, n_sites, n_groups, K_max, nb));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nested_laplace_nmix_icar
Rcpp::List cpp_nested_laplace_nmix_icar(Rcpp::IntegerVector y, Rcpp::IntegerVector site_idx, Rcpp::IntegerVector map_site_to_unit_R, Rcpp::NumericMatrix X_lambda_R, Rcpp::NumericMatrix X_p_R, Rcpp::IntegerVector adj_row_ptr, Rcpp::IntegerVector adj_col_idx, Rcpp::IntegerVector n_neighbors, int n_spatial, Rcpp::NumericVector tau_grid, Rcpp::NumericVector r_grid, Rcpp::NumericVector beta_lambda_init, Rcpp::NumericVector beta_p_init, Rcpp::Nullable<Rcpp::NumericVector> z_init, int K_max, int max_iter, double tol, bool verbose, bool progress, int progress_every, double progress_throttle, std::string progress_file);
RcppExport SEXP _tulpaObs_cpp_nested_laplace_nmix_icar(SEXP ySEXP, SEXP site_idxSEXP, SEXP map_site_to_unit_RSEXP, SEXP X_lambda_RSEXP, SEXP X_p_RSEXP, SEXP adj_row_ptrSEXP, SEXP adj_col_idxSEXP, SEXP n_neighborsSEXP, SEXP n_spatialSEXP, SEXP tau_gridSEXP, SEXP r_gridSEXP, SEXP beta_lambda_initSEXP, SEXP beta_p_initSEXP, SEXP z_initSEXP, SEXP K_maxSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP progressSEXP, SEXP progress_everySEXP, SEXP progress_throttleSEXP, SEXP progress_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_idx(site_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type map_site_to_unit_R(map_site_to_unit_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda_R(X_lambda_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_p_R(X_p_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_row_ptr(adj_row_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_col_idx(adj_col_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type n_spatial(n_spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tau_grid(tau_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r_grid(r_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_lambda_init(beta_lambda_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_p_init(beta_p_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type z_init(z_initSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_every(progress_everySEXP);
    Rcpp::traits::input_parameter< double >::type progress_throttle(progress_throttleSEXP);
    Rcpp::traits::input_parameter< std::string >::type progress_file(progress_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nested_laplace_nmix_icar(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, beta_lambda_init, beta_p_init, z_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nested_laplace_nmix_car_proper
Rcpp::List cpp_nested_laplace_nmix_car_proper(Rcpp::IntegerVector y, Rcpp::IntegerVector site_idx, Rcpp::IntegerVector map_site_to_unit_R, Rcpp::NumericMatrix X_lambda_R, Rcpp::NumericMatrix X_p_R, Rcpp::IntegerVector adj_row_ptr, Rcpp::IntegerVector adj_col_idx, Rcpp::IntegerVector n_neighbors, int n_spatial, Rcpp::NumericVector tau_grid, Rcpp::NumericVector rho_grid, Rcpp::NumericVector r_grid, Rcpp::NumericVector beta_lambda_init, Rcpp::NumericVector beta_p_init, Rcpp::Nullable<Rcpp::NumericVector> z_init, int K_max, int max_iter, double tol, bool verbose, bool progress, int progress_every, double progress_throttle, std::string progress_file);
RcppExport SEXP _tulpaObs_cpp_nested_laplace_nmix_car_proper(SEXP ySEXP, SEXP site_idxSEXP, SEXP map_site_to_unit_RSEXP, SEXP X_lambda_RSEXP, SEXP X_p_RSEXP, SEXP adj_row_ptrSEXP, SEXP adj_col_idxSEXP, SEXP n_neighborsSEXP, SEXP n_spatialSEXP, SEXP tau_gridSEXP, SEXP rho_gridSEXP, SEXP r_gridSEXP, SEXP beta_lambda_initSEXP, SEXP beta_p_initSEXP, SEXP z_initSEXP, SEXP K_maxSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP progressSEXP, SEXP progress_everySEXP, SEXP progress_throttleSEXP, SEXP progress_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_idx(site_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type map_site_to_unit_R(map_site_to_unit_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda_R(X_lambda_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_p_R(X_p_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_row_ptr(adj_row_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_col_idx(adj_col_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type n_spatial(n_spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tau_grid(tau_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rho_grid(rho_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r_grid(r_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_lambda_init(beta_lambda_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_p_init(beta_p_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type z_init(z_initSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_every(progress_everySEXP);
    Rcpp::traits::input_parameter< double >::type progress_throttle(progress_throttleSEXP);
    Rcpp::traits::input_parameter< std::string >::type progress_file(progress_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nested_laplace_nmix_car_proper(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, r_grid, beta_lambda_init, beta_p_init, z_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nested_laplace_nmix_bym2
Rcpp::List cpp_nested_laplace_nmix_bym2(Rcpp::IntegerVector y, Rcpp::IntegerVector site_idx, Rcpp::IntegerVector map_site_to_unit_R, Rcpp::NumericMatrix X_lambda_R, Rcpp::NumericMatrix X_p_R, Rcpp::IntegerVector adj_row_ptr, Rcpp::IntegerVector adj_col_idx, Rcpp::IntegerVector n_neighbors, int n_spatial, Rcpp::NumericVector sigma_grid, Rcpp::NumericVector rho_grid, Rcpp::NumericVector r_grid, double scale_factor, Rcpp::NumericVector beta_lambda_init, Rcpp::NumericVector beta_p_init, Rcpp::Nullable<Rcpp::NumericVector> v_init, Rcpp::Nullable<Rcpp::NumericVector> w_init, int K_max, int max_iter, double tol, bool verbose, bool progress, int progress_every, double progress_throttle, std::string progress_file);
RcppExport SEXP _tulpaObs_cpp_nested_laplace_nmix_bym2(SEXP ySEXP, SEXP site_idxSEXP, SEXP map_site_to_unit_RSEXP, SEXP X_lambda_RSEXP, SEXP X_p_RSEXP, SEXP adj_row_ptrSEXP, SEXP adj_col_idxSEXP, SEXP n_neighborsSEXP, SEXP n_spatialSEXP, SEXP sigma_gridSEXP, SEXP rho_gridSEXP, SEXP r_gridSEXP, SEXP scale_factorSEXP, SEXP beta_lambda_initSEXP, SEXP beta_p_initSEXP, SEXP v_initSEXP, SEXP w_initSEXP, SEXP K_maxSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP progressSEXP, SEXP progress_everySEXP, SEXP progress_throttleSEXP, SEXP progress_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_idx(site_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type map_site_to_unit_R(map_site_to_unit_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda_R(X_lambda_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_p_R(X_p_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_row_ptr(adj_row_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type adj_col_idx(adj_col_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type n_spatial(n_spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma_grid(sigma_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rho_grid(rho_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r_grid(r_gridSEXP);
    Rcpp::traits::input_parameter< double >::type scale_factor(scale_factorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_lambda_init(beta_lambda_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_p_init(beta_p_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type v_init(v_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type w_init(w_initSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_every(progress_everySEXP);
    Rcpp::traits::input_parameter< double >::type progress_throttle(progress_throttleSEXP);
    Rcpp::traits::input_parameter< std::string >::type progress_file(progress_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nested_laplace_nmix_bym2(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, r_grid, scale_factor, beta_lambda_init, beta_p_init, v_init, w_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nested_laplace_nmix_spde
Rcpp::List cpp_nested_laplace_nmix_spde(Rcpp::IntegerVector y, Rcpp::IntegerVector site_idx, Rcpp::NumericMatrix X_lambda_R, Rcpp::NumericMatrix X_p_R, Rcpp::NumericMatrix A_R, Rcpp::List Q_list, Rcpp::NumericVector log_det_Q, Rcpp::NumericMatrix theta_grid_R, Rcpp::NumericVector r_grid, Rcpp::NumericVector beta_lambda_init, Rcpp::NumericVector beta_p_init, Rcpp::Nullable<Rcpp::NumericVector> u_init, int K_max, int max_iter, double tol, bool verbose, bool progress, int progress_every, double progress_throttle, std::string progress_file);
RcppExport SEXP _tulpaObs_cpp_nested_laplace_nmix_spde(SEXP ySEXP, SEXP site_idxSEXP, SEXP X_lambda_RSEXP, SEXP X_p_RSEXP, SEXP A_RSEXP, SEXP Q_listSEXP, SEXP log_det_QSEXP, SEXP theta_grid_RSEXP, SEXP r_gridSEXP, SEXP beta_lambda_initSEXP, SEXP beta_p_initSEXP, SEXP u_initSEXP, SEXP K_maxSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP progressSEXP, SEXP progress_everySEXP, SEXP progress_throttleSEXP, SEXP progress_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type site_idx(site_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_lambda_R(X_lambda_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_p_R(X_p_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A_R(A_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Q_list(Q_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type log_det_Q(log_det_QSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type theta_grid_R(theta_grid_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r_grid(r_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_lambda_init(beta_lambda_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_p_init(beta_p_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type u_init(u_initSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_every(progress_everySEXP);
    Rcpp::traits::input_parameter< double >::type progress_throttle(progress_throttleSEXP);
    Rcpp::traits::input_parameter< std::string >::type progress_file(progress_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nested_laplace_nmix_spde(y, site_idx, X_lambda_R, X_p_R, A_R, Q_list, log_det_Q, theta_grid_R, r_grid, beta_lambda_init, beta_p_init, u_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file));
    return rcpp_result_gen;
END_RCPP
}
// occ_make_nested_likelihood
SEXP occ_make_nested_likelihood(Rcpp::NumericVector y, Rcpp::NumericVector det_prob);
RcppExport SEXP _tulpaObs_occ_make_nested_likelihood(SEXP ySEXP, SEXP det_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type det_prob(det_probSEXP);
    rcpp_result_gen = Rcpp::wrap(occ_make_nested_likelihood(y, det_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_occu_fit
Rcpp::List cpp_occu_fit(Rcpp::List spec_r);
RcppExport SEXP _tulpaObs_cpp_occu_fit(SEXP spec_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec_r(spec_rSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_occu_fit(spec_r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tulpaObs_cpp_register_occu_cover_lognormal_coupling", (DL_FUNC) &_tulpaObs_cpp_register_occu_cover_lognormal_coupling, 0},
    {"_tulpaObs_cpp_register_occu_cover_beta_coupling", (DL_FUNC) &_tulpaObs_cpp_register_occu_cover_beta_coupling, 0},
    {"_tulpaObs_cpp_eval_occu_cover_lognormal_cell", (DL_FUNC) &_tulpaObs_cpp_eval_occu_cover_lognormal_cell, 7},
    {"_tulpaObs_cpp_eval_occu_cover_beta_cell", (DL_FUNC) &_tulpaObs_cpp_eval_occu_cover_beta_cell, 7},
    {"_tulpaObs_cpp_register_occu_multiscale_cover_coupling", (DL_FUNC) &_tulpaObs_cpp_register_occu_multiscale_cover_coupling, 3},
    {"_tulpaObs_cpp_eval_occu_multiscale_cover_lognormal_cell", (DL_FUNC) &_tulpaObs_cpp_eval_occu_multiscale_cover_lognormal_cell, 9},
    {"_tulpaObs_cpp_eval_occu_multiscale_cover_beta_cell", (DL_FUNC) &_tulpaObs_cpp_eval_occu_multiscale_cover_beta_cell, 9},
    {"_tulpaObs_cpp_nmix_community_em", (DL_FUNC) &_tulpaObs_cpp_nmix_community_em, 10},
    {"_tulpaObs_cpp_nmix_community_field_solve", (DL_FUNC) &_tulpaObs_cpp_nmix_community_field_solve, 20},
    {"_tulpaObs_cpp_nmix_community_oracle", (DL_FUNC) &_tulpaObs_cpp_nmix_community_oracle, 9},
    {"_tulpaObs_cpp_nmix_community_spatial_icar", (DL_FUNC) &_tulpaObs_cpp_nmix_community_spatial_icar, 22},
    {"_tulpaObs_cpp_nmix_community_spatial_car_proper", (DL_FUNC) &_tulpaObs_cpp_nmix_community_spatial_car_proper, 24},
    {"_tulpaObs_cpp_nmix_community_spatial_bym2", (DL_FUNC) &_tulpaObs_cpp_nmix_community_spatial_bym2, 24},
    {"_tulpaObs_cpp_nmix_community_spatial_spde", (DL_FUNC) &_tulpaObs_cpp_nmix_community_spatial_spde, 20},
    {"_tulpaObs_cpp_nmix_spatial_community_oracle", (DL_FUNC) &_tulpaObs_cpp_nmix_spatial_community_oracle, 8},
    {"_tulpaObs_cpp_nmix_spatial_community_set_offset", (DL_FUNC) &_tulpaObs_cpp_nmix_spatial_community_set_offset, 2},
    {"_tulpaObs_cpp_nmix_laplace_fixed", (DL_FUNC) &_tulpaObs_cpp_nmix_laplace_fixed, 13},
    {"_tulpaObs_cpp_nmix_total_log_lik", (DL_FUNC) &_tulpaObs_cpp_nmix_total_log_lik, 6},
    {"_tulpaObs_cpp_nmix_grouped_oracle", (DL_FUNC) &_tulpaObs_cpp_nmix_grouped_oracle, 11},
    {"_tulpaObs_cpp_nested_laplace_nmix_icar", (DL_FUNC) &_tulpaObs_cpp_nested_laplace_nmix_icar, 22},
    {"_tulpaObs_cpp_nested_laplace_nmix_car_proper", (DL_FUNC) &_tulpaObs_cpp_nested_laplace_nmix_car_proper, 23},
    {"_tulpaObs_cpp_nested_laplace_nmix_bym2", (DL_FUNC) &_tulpaObs_cpp_nested_laplace_nmix_bym2, 25},
    {"_tulpaObs_cpp_nested_laplace_nmix_spde", (DL_FUNC) &_tulpaObs_cpp_nested_laplace_nmix_spde, 20},
    {"_tulpaObs_occ_make_nested_likelihood", (DL_FUNC) &_tulpaObs_occ_make_nested_likelihood, 2},
    {"_tulpaObs_cpp_occu_fit", (DL_FUNC) &_tulpaObs_cpp_occu_fit, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_tulpaObs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
