# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_abun_nuts_joint_logpost <- function(spec, theta, sigma_beta, sigma_logr) {
    .Call(`_tulpaObs_cpp_abun_nuts_joint_logpost`, spec, theta, sigma_beta, sigma_logr)
}

cpp_abun_nuts <- function(spec, theta0, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_abun_nuts`, spec, theta0, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_register_occu_cover_lognormal_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_lognormal_coupling`))
}

cpp_register_occu_cover_beta_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_beta_coupling`))
}

cpp_register_occu_cover_lognormal_agg_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_lognormal_agg_coupling`))
}

cpp_register_occu_cover_beta_agg_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_beta_agg_coupling`))
}

cpp_eval_occu_cover_lognormal_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_lognormal_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature)
}

cpp_eval_occu_cover_beta_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos, phi_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_beta_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos, phi_pos, curvature)
}

cpp_eval_occu_cover_lognormal_agg_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_lognormal_agg_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature)
}

cpp_eval_occu_cover_beta_agg_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos, phi_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_beta_agg_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos, phi_pos, curvature)
}

cpp_register_occu_cover_lognormal_latent_coupling <- function(cover_values, sigma_eps, n_quad = 1L) {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_lognormal_latent_coupling`, cover_values, sigma_eps, n_quad))
}

cpp_register_occu_cover_beta_latent_coupling <- function(cover_values, phi_prec, n_quad = 15L) {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_beta_latent_coupling`, cover_values, phi_prec, n_quad))
}

cpp_eval_occu_cover_lognormal_latent_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos_vals, sigma_eps, sigma_u, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_lognormal_latent_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos_vals, sigma_eps, sigma_u, curvature)
}

cpp_eval_occu_cover_beta_latent_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos_vals, phi_prec, sigma_u, n_quad = 15L, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_beta_latent_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos_vals, phi_prec, sigma_u, n_quad, curvature)
}

cpp_register_occu_multiscale_cover_coupling <- function(positive, n_plots_per_cell, plot_sizes_flat) {
    .Call(`_tulpaObs_cpp_register_occu_multiscale_cover_coupling`, positive, n_plots_per_cell, plot_sizes_flat)
}

cpp_eval_occu_multiscale_cover_lognormal_cell <- function(eta_psi, eta_theta, eta_p, eta_pos, y_det, y_pos, plot_sizes, sigma_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_multiscale_cover_lognormal_cell`, eta_psi, eta_theta, eta_p, eta_pos, y_det, y_pos, plot_sizes, sigma_pos, curvature)
}

cpp_eval_occu_multiscale_cover_beta_cell <- function(eta_psi, eta_theta, eta_p, eta_pos, y_det, y_pos, plot_sizes, phi_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_multiscale_cover_beta_cell`, eta_psi, eta_theta, eta_p, eta_pos, y_det, y_pos, plot_sizes, phi_pos, curvature)
}

cpp_distance_laplace_fixed <- function(y, X_lambda_R, X_sigma_R, cutpoints, transect, key, beta_lambda_init, beta_sigma_init, eta_b_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max, quad_order) {
    .Call(`_tulpaObs_cpp_distance_laplace_fixed`, y, X_lambda_R, X_sigma_R, cutpoints, transect, key, beta_lambda_init, beta_sigma_init, eta_b_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max, quad_order)
}

cpp_distance_total_log_lik <- function(y, eta_lambda, eta_sigma, eta_b, cutpoints, transect, key, K_max, r, quad_order) {
    .Call(`_tulpaObs_cpp_distance_total_log_lik`, y, eta_lambda, eta_sigma, eta_b, cutpoints, transect, key, K_max, r, quad_order)
}

cpp_distance_site_sweep <- function(y_bins, eta_lambda, eta_sigma, cutpoints, transect, quad_order, K_max, nb, r) {
    .Call(`_tulpaObs_cpp_distance_site_sweep`, y_bins, eta_lambda, eta_sigma, cutpoints, transect, quad_order, K_max, nb, r)
}

cpp_distance_nuts_joint_logpost <- function(spec, theta, sigma_beta, sigma_shape, sigma_logr) {
    .Call(`_tulpaObs_cpp_distance_nuts_joint_logpost`, spec, theta, sigma_beta, sigma_shape, sigma_logr)
}

cpp_distance_nuts <- function(spec, theta0, sigma_beta, sigma_shape, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_distance_nuts`, spec, theta0, sigma_beta, sigma_shape, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_distance_grouped_oracle <- function(arm, y_bins, X_lambda, X_sigma, Z_site, site_group, n_sites, n_groups, cutpoints, transect, quad_order, K_max, nb = FALSE) {
    .Call(`_tulpaObs_cpp_distance_grouped_oracle`, arm, y_bins, X_lambda, X_sigma, Z_site, site_group, n_sites, n_groups, cutpoints, transect, quad_order, K_max, nb)
}

cpp_dyn_abun_total_log_lik <- function(y, n_sites, T, J, K, eta_lambda, eta_p, eta_omega, eta_gamma, use_nb = FALSE, eta_logr = 0.0) {
    .Call(`_tulpaObs_cpp_dyn_abun_total_log_lik`, y, n_sites, T, J, K, eta_lambda, eta_p, eta_omega, eta_gamma, use_nb, eta_logr)
}

cpp_dyn_abun_init_weights_mat <- function(y, n_sites, T, J, K, site, eta_p, eta_omega, eta_gamma) {
    .Call(`_tulpaObs_cpp_dyn_abun_init_weights_mat`, y, n_sites, T, J, K, site, eta_p, eta_omega, eta_gamma)
}

cpp_dyn_abun_init_loglik <- function(C, eta_lambda, use_nb = FALSE, eta_logr = 0.0, deriv = TRUE) {
    .Call(`_tulpaObs_cpp_dyn_abun_init_loglik`, C, eta_lambda, use_nb, eta_logr, deriv)
}

cpp_dyn_abun_nuts_joint_logpost <- function(spec, theta, sigma_beta) {
    .Call(`_tulpaObs_cpp_dyn_abun_nuts_joint_logpost`, spec, theta, sigma_beta)
}

cpp_dyn_abun_nuts <- function(spec, theta0, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_dyn_abun_nuts`, spec, theta0, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_fp_occu_total_log_lik <- function(y, site_idx, eta_psi, eta_p11, eta_p10, eta_b) {
    .Call(`_tulpaObs_cpp_fp_occu_total_log_lik`, y, site_idx, eta_psi, eta_p11, eta_p10, eta_b)
}

cpp_fp_occu_nuts_joint_logpost <- function(spec, theta, sigma_beta) {
    .Call(`_tulpaObs_cpp_fp_occu_nuts_joint_logpost`, spec, theta, sigma_beta)
}

cpp_fp_occu_nuts <- function(spec, theta0, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_fp_occu_nuts`, spec, theta0, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_ms_abun_nuts_joint_logpost <- function(spec, theta, pri, sigma_beta, sigma_logr) {
    .Call(`_tulpaObs_cpp_ms_abun_nuts_joint_logpost`, spec, theta, pri, sigma_beta, sigma_logr)
}

cpp_ms_abun_nuts <- function(spec, theta0, pri, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_ms_abun_nuts`, spec, theta0, pri, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_ms_ocs_marginal_grad <- function(spec, theta_inner) {
    .Call(`_tulpaObs_cpp_ms_ocs_marginal_grad`, spec, theta_inner)
}

cpp_ms_ocs_marginal_ll <- function(spec, theta_inner) {
    .Call(`_tulpaObs_cpp_ms_ocs_marginal_ll`, spec, theta_inner)
}

cpp_ms_ocs_joint_logpost <- function(spec, theta, pri, sigma_beta, sd_L, constrain = FALSE) {
    .Call(`_tulpaObs_cpp_ms_ocs_joint_logpost`, spec, theta, pri, sigma_beta, sd_L, constrain)
}

cpp_ms_ocs_nuts <- function(spec, theta0, pri, sigma_beta, sd_L, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose, constrain = FALSE) {
    .Call(`_tulpaObs_cpp_ms_ocs_nuts`, spec, theta0, pri, sigma_beta, sd_L, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose, constrain)
}

cpp_nmix_community_em <- function(oracle, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter = 100L, tol = 1e-6, inner_max = 50L, inner_tol = 1e-8, sigma_beta = 100.0, verbose = FALSE) {
    .Call(`_tulpaObs_cpp_nmix_community_em`, oracle, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter, tol, inner_max, inner_tol, sigma_beta, verbose)
}

cpp_nmix_community_field_solve <- function(y, site_idx, species_idx, X_lambda, X_p, coef_lambda, coef_p, map_site_to_unit_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau, rho, log_det_Q_rho, z_init, K_max, max_iter = 100L, tol = 1e-6, verbose = FALSE) {
    .Call(`_tulpaObs_cpp_nmix_community_field_solve`, y, site_idx, species_idx, X_lambda, X_p, coef_lambda, coef_p, map_site_to_unit_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau, rho, log_det_Q_rho, z_init, K_max, max_iter, tol, verbose)
}

cpp_nmix_community_oracle <- function(y, site_idx, species_idx, X_lambda, X_p, n_sites, n_species, K_max, nb = FALSE) {
    .Call(`_tulpaObs_cpp_nmix_community_oracle`, y, site_idx, species_idx, X_lambda, X_p, n_sites, n_species, K_max, nb)
}

cpp_nmix_community_spatial_icar <- function(oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em = 100L, tol_em = 1e-4, inner_max = 50L, inner_tol = 1e-6, sigma_beta = 100.0, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nmix_community_spatial_icar`, oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nmix_community_spatial_car_proper <- function(oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, log_det_Q_rho, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em = 100L, tol_em = 1e-4, inner_max = 50L, inner_tol = 1e-6, sigma_beta = 100.0, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nmix_community_spatial_car_proper`, oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, log_det_Q_rho, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nmix_community_spatial_bym2 <- function(oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, scale_factor, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em = 100L, tol_em = 1e-4, inner_max = 50L, inner_tol = 1e-6, sigma_beta = 100.0, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nmix_community_spatial_bym2`, oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, scale_factor, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nmix_community_spatial_spde <- function(oracle, X_lambda_R, A_R, Q_list, log_det_Q, theta_grid_R, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em = 100L, tol_em = 1e-4, inner_max = 50L, inner_tol = 1e-6, sigma_beta = 100.0, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nmix_community_spatial_spde`, oracle, X_lambda_R, A_R, Q_list, log_det_Q, theta_grid_R, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nmix_spatial_community_oracle <- function(y, site_idx, species_idx, X_lambda, X_p, n_sites, n_species, K_max) {
    .Call(`_tulpaObs_cpp_nmix_spatial_community_oracle`, y, site_idx, species_idx, X_lambda, X_p, n_sites, n_species, K_max)
}

cpp_nmix_spatial_community_set_offset <- function(oracle_ptr, z) {
    invisible(.Call(`_tulpaObs_cpp_nmix_spatial_community_set_offset`, oracle_ptr, z))
}

cpp_nmix_laplace_fixed <- function(y, site_idx, X_lambda_R, X_p_R, beta_lambda_init, beta_p_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max) {
    .Call(`_tulpaObs_cpp_nmix_laplace_fixed`, y, site_idx, X_lambda_R, X_p_R, beta_lambda_init, beta_p_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max)
}

cpp_nmix_total_log_lik <- function(y, site_idx, eta_p, eta_lambda, K_max, r) {
    .Call(`_tulpaObs_cpp_nmix_total_log_lik`, y, site_idx, eta_p, eta_lambda, K_max, r)
}

cpp_nmix_grouped_oracle <- function(arm, y, site_idx, X_lambda, X_p, Z_site, site_group, n_sites, n_groups, K_max, nb = FALSE) {
    .Call(`_tulpaObs_cpp_nmix_grouped_oracle`, arm, y, site_idx, X_lambda, X_p, Z_site, site_group, n_sites, n_groups, K_max, nb)
}

cpp_nested_laplace_nmix_icar <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, beta_lambda_init, beta_p_init, z_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_nmix_icar`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, beta_lambda_init, beta_p_init, z_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nested_laplace_nmix_car_proper <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, r_grid, beta_lambda_init, beta_p_init, z_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_nmix_car_proper`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, r_grid, beta_lambda_init, beta_p_init, z_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nested_laplace_nmix_bym2 <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, r_grid, scale_factor, beta_lambda_init, beta_p_init, v_init = NULL, w_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_nmix_bym2`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, r_grid, scale_factor, beta_lambda_init, beta_p_init, v_init, w_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nested_laplace_nmix_spde <- function(y, site_idx, X_lambda_R, X_p_R, A_R, Q_list, log_det_Q, theta_grid_R, r_grid, beta_lambda_init, beta_p_init, u_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_nmix_spde`, y, site_idx, X_lambda_R, X_p_R, A_R, Q_list, log_det_Q, theta_grid_R, r_grid, beta_lambda_init, beta_p_init, u_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

occ_make_nested_likelihood <- function(y, det_prob) {
    .Call(`_tulpaObs_occ_make_nested_likelihood`, y, det_prob)
}

cpp_occu_fit <- function(spec_r) {
    .Call(`_tulpaObs_cpp_occu_fit`, spec_r)
}

cpp_removal_laplace_fixed <- function(y, site_idx, X_lambda_R, X_p_R, beta_lambda_init, beta_p_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max) {
    .Call(`_tulpaObs_cpp_removal_laplace_fixed`, y, site_idx, X_lambda_R, X_p_R, beta_lambda_init, beta_p_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max)
}

cpp_removal_total_log_lik <- function(y, site_idx, eta_p, eta_lambda, K_max, r) {
    .Call(`_tulpaObs_cpp_removal_total_log_lik`, y, site_idx, eta_p, eta_lambda, K_max, r)
}

cpp_removal_nuts_joint_logpost <- function(spec, theta, sigma_beta, sigma_logr) {
    .Call(`_tulpaObs_cpp_removal_nuts_joint_logpost`, spec, theta, sigma_beta, sigma_logr)
}

cpp_removal_nuts <- function(spec, theta0, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_removal_nuts`, spec, theta0, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_removal_grouped_oracle <- function(arm, y, site_idx, X_lambda, X_p, Z_site, site_group, n_sites, n_groups, K_max, nb = FALSE) {
    .Call(`_tulpaObs_cpp_removal_grouped_oracle`, arm, y, site_idx, X_lambda, X_p, Z_site, site_group, n_sites, n_groups, K_max, nb)
}

cpp_nested_laplace_removal_icar <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, beta_lambda_init, beta_p_init, z_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_removal_icar`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, beta_lambda_init, beta_p_init, z_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nested_laplace_removal_bym2 <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, r_grid, scale_factor, beta_lambda_init, beta_p_init, v_init = NULL, w_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_removal_bym2`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, r_grid, scale_factor, beta_lambda_init, beta_p_init, v_init, w_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nested_laplace_removal_car_proper <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, r_grid, beta_lambda_init, beta_p_init, z_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_removal_car_proper`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, r_grid, beta_lambda_init, beta_p_init, z_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

