# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_abun_nuts_joint_logpost <- function(spec, theta, sigma_beta, sigma_logr) {
    .Call(`_tulpaObs_cpp_abun_nuts_joint_logpost`, spec, theta, sigma_beta, sigma_logr)
}

cpp_abun_nuts <- function(spec, theta0, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_abun_nuts`, spec, theta0, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_register_occu_cover_lognormal_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_lognormal_coupling`))
}

cpp_register_occu_cover_beta_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_beta_coupling`))
}

cpp_register_occu_cover_gaussian_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_gaussian_coupling`))
}

cpp_register_occu_cover_lognormal_agg_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_lognormal_agg_coupling`))
}

cpp_register_occu_cover_beta_agg_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_beta_agg_coupling`))
}

cpp_register_occu_cover_gaussian_agg_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_gaussian_agg_coupling`))
}

cpp_eval_occu_cover_lognormal_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_lognormal_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature)
}

cpp_eval_occu_cover_beta_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos, phi_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_beta_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos, phi_pos, curvature)
}

cpp_eval_occu_cover_gaussian_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_gaussian_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature)
}

cpp_eval_occu_cover_lognormal_agg_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_lognormal_agg_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos, sigma_pos, curvature)
}

cpp_eval_occu_cover_beta_agg_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos, phi_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_beta_agg_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos, phi_pos, curvature)
}

cpp_register_occu_cover_lognormal_latent_coupling <- function(cover_values, sigma_eps, n_quad = 1L) {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_lognormal_latent_coupling`, cover_values, sigma_eps, n_quad))
}

cpp_register_occu_cover_beta_latent_coupling <- function(cover_values, phi_prec, n_quad = 15L) {
    invisible(.Call(`_tulpaObs_cpp_register_occu_cover_beta_latent_coupling`, cover_values, phi_prec, n_quad))
}

cpp_eval_occu_cover_lognormal_latent_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos_vals, sigma_eps, sigma_u, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_lognormal_latent_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos_vals, sigma_eps, sigma_u, curvature)
}

cpp_eval_occu_cover_beta_latent_cell <- function(eta_psi, eta_p, eta_pos, y_det, y_pos_vals, phi_prec, sigma_u, n_quad = 15L, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_cover_beta_latent_cell`, eta_psi, eta_p, eta_pos, y_det, y_pos_vals, phi_prec, sigma_u, n_quad, curvature)
}

cpp_register_occu_multiscale_cover_coupling <- function(positive, n_plots_per_cell, plot_sizes_flat) {
    .Call(`_tulpaObs_cpp_register_occu_multiscale_cover_coupling`, positive, n_plots_per_cell, plot_sizes_flat)
}

cpp_eval_occu_multiscale_cover_lognormal_cell <- function(eta_psi, eta_theta, eta_p, eta_pos, y_det, y_pos, plot_sizes, sigma_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_multiscale_cover_lognormal_cell`, eta_psi, eta_theta, eta_p, eta_pos, y_det, y_pos, plot_sizes, sigma_pos, curvature)
}

cpp_eval_occu_multiscale_cover_beta_cell <- function(eta_psi, eta_theta, eta_p, eta_pos, y_det, y_pos, plot_sizes, phi_pos, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_multiscale_cover_beta_cell`, eta_psi, eta_theta, eta_p, eta_pos, y_det, y_pos, plot_sizes, phi_pos, curvature)
}

cpp_register_occu_only_coupling <- function() {
    invisible(.Call(`_tulpaObs_cpp_register_occu_only_coupling`))
}

cpp_eval_occu_only_cell <- function(eta_psi, eta_p, y_det, curvature = "observed") {
    .Call(`_tulpaObs_cpp_eval_occu_only_cell`, eta_psi, eta_p, y_det, curvature)
}

cpp_cover_pit_cdf <- function(eta_occ, eta_pos, occur, y_pos, pos_col, disp, positive, lower, upper, trunc_upper) {
    .Call(`_tulpaObs_cpp_cover_pit_cdf`, eta_occ, eta_pos, occur, y_pos, pos_col, disp, positive, lower, upper, trunc_upper)
}

cpp_cover_ppc <- function(eta_occ, eta_pos, occur, y_pos_nat, disp, trunc_upper, positive, freeman) {
    .Call(`_tulpaObs_cpp_cover_ppc`, eta_occ, eta_pos, occur, y_pos_nat, disp, trunc_upper, positive, freeman)
}

cpp_cover_hurdle_ploglik <- function(eta_occ, eta_pos, disp, occur, y_pos, pos_col, positive, lower, upper, trunc_upper, n_threads) {
    .Call(`_tulpaObs_cpp_cover_hurdle_ploglik`, eta_occ, eta_pos, disp, occur, y_pos, pos_col, positive, lower, upper, trunc_upper, n_threads)
}

cpp_cover_nuts_logpost <- function(spec, theta, sigma_beta, sigma_logdisp) {
    .Call(`_tulpaObs_cpp_cover_nuts_logpost`, spec, theta, sigma_beta, sigma_logdisp)
}

cpp_cover_nuts <- function(spec, theta0, sigma_beta, sigma_logdisp, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_cover_nuts`, spec, theta0, sigma_beta, sigma_logdisp, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_distance_laplace_fixed <- function(y, X_lambda_R, X_sigma_R, quad_xptr, key, beta_lambda_init, beta_sigma_init, eta_b_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max) {
    .Call(`_tulpaObs_cpp_distance_laplace_fixed`, y, X_lambda_R, X_sigma_R, quad_xptr, key, beta_lambda_init, beta_sigma_init, eta_b_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max)
}

cpp_distance_total_log_lik <- function(y, eta_lambda, eta_sigma, eta_b, quad_xptr, key, K_max, r) {
    .Call(`_tulpaObs_cpp_distance_total_log_lik`, y, eta_lambda, eta_sigma, eta_b, quad_xptr, key, K_max, r)
}

cpp_distance_site_sweep <- function(y_bins, eta_lambda, eta_sigma, quad_xptr, K_max, nb, r, key = 0L, eta_b = 0.0, value_only = FALSE) {
    .Call(`_tulpaObs_cpp_distance_site_sweep`, y_bins, eta_lambda, eta_sigma, quad_xptr, K_max, nb, r, key, eta_b, value_only)
}

cpp_distance_nuts_joint_logpost <- function(spec, theta, sigma_beta, sigma_shape, sigma_logr) {
    .Call(`_tulpaObs_cpp_distance_nuts_joint_logpost`, spec, theta, sigma_beta, sigma_shape, sigma_logr)
}

cpp_distance_nuts <- function(spec, theta0, sigma_beta, sigma_shape, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_distance_nuts`, spec, theta0, sigma_beta, sigma_shape, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_distance_ploglik_batch <- function(y, quad_xptr, key, K_max, eta_lambda, eta_sigma, eta_b, r_vec, n_threads) {
    .Call(`_tulpaObs_cpp_distance_ploglik_batch`, y, quad_xptr, key, K_max, eta_lambda, eta_sigma, eta_b, r_vec, n_threads)
}

cpp_distance_build_quad <- function(cutpoints, transect, quad_order) {
    .Call(`_tulpaObs_cpp_distance_build_quad`, cutpoints, transect, quad_order)
}

cpp_distance_grouped_oracle <- function(arm, y_bins, X_lambda, X_sigma, Z_site, site_group, n_sites, n_groups, quad_xptr, K_max, nb = FALSE, key = 0L, eta_b = 0.0) {
    .Call(`_tulpaObs_cpp_distance_grouped_oracle`, arm, y_bins, X_lambda, X_sigma, Z_site, site_group, n_sites, n_groups, quad_xptr, K_max, nb, key, eta_b)
}

cpp_dyn_abun_total_log_lik <- function(y, n_sites, T, J, K, eta_lambda, eta_p, eta_omega, eta_gamma, use_nb = FALSE, eta_logr = 0.0) {
    .Call(`_tulpaObs_cpp_dyn_abun_total_log_lik`, y, n_sites, T, J, K, eta_lambda, eta_p, eta_omega, eta_gamma, use_nb, eta_logr)
}

cpp_dyn_abun_dynamics_log_lik <- function(y, n_sites, T, J, K, eta_lambda, eta_p, eta_omega, eta_gamma, dynamics, use_nb = FALSE, eta_logr = 0.0) {
    .Call(`_tulpaObs_cpp_dyn_abun_dynamics_log_lik`, y, n_sites, T, J, K, eta_lambda, eta_p, eta_omega, eta_gamma, dynamics, use_nb, eta_logr)
}

cpp_dyn_abun_init_weights_mat <- function(y, n_sites, T, J, K, site, eta_p, eta_omega, eta_gamma) {
    .Call(`_tulpaObs_cpp_dyn_abun_init_weights_mat`, y, n_sites, T, J, K, site, eta_p, eta_omega, eta_gamma)
}

cpp_dyn_abun_init_loglik <- function(C, eta_lambda, use_nb = FALSE, eta_logr = 0.0, deriv = TRUE) {
    .Call(`_tulpaObs_cpp_dyn_abun_init_loglik`, C, eta_lambda, use_nb, eta_logr, deriv)
}

cpp_dyn_abun_p_loglik <- function(y, n_sites, T, J, K, site, eta_lambda, eta_p, eta_omega, eta_gamma, use_nb = FALSE, eta_logr = 0.0, deriv = TRUE) {
    .Call(`_tulpaObs_cpp_dyn_abun_p_loglik`, y, n_sites, T, J, K, site, eta_lambda, eta_p, eta_omega, eta_gamma, use_nb, eta_logr, deriv)
}

cpp_dyn_abun_nuts_joint_logpost <- function(spec, theta, sigma_beta) {
    .Call(`_tulpaObs_cpp_dyn_abun_nuts_joint_logpost`, spec, theta, sigma_beta)
}

cpp_dyn_abun_nuts <- function(spec, theta0, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_dyn_abun_nuts`, spec, theta0, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_dyn_abun_ploglik_batch <- function(y_flat, n_sites, T, J, K, eta_lambda, eta_p, eta_omega, eta_gamma, use_nb, eta_logr, n_threads) {
    .Call(`_tulpaObs_cpp_dyn_abun_ploglik_batch`, y_flat, n_sites, T, J, K, eta_lambda, eta_p, eta_omega, eta_gamma, use_nb, eta_logr, n_threads)
}

cpp_fp_occu_total_log_lik <- function(y, site_idx, eta_psi, eta_p11, eta_p10, eta_b) {
    .Call(`_tulpaObs_cpp_fp_occu_total_log_lik`, y, site_idx, eta_psi, eta_p11, eta_p10, eta_b)
}

cpp_fp_occu_nuts_joint_logpost <- function(spec, theta, sigma_beta) {
    .Call(`_tulpaObs_cpp_fp_occu_nuts_joint_logpost`, spec, theta, sigma_beta)
}

cpp_fp_occu_nuts <- function(spec, theta0, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_fp_occu_nuts`, spec, theta0, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_ms_abun_nuts_joint_logpost <- function(spec, theta, pri, sigma_beta, sigma_logr) {
    .Call(`_tulpaObs_cpp_ms_abun_nuts_joint_logpost`, spec, theta, pri, sigma_beta, sigma_logr)
}

cpp_ms_abun_nuts <- function(spec, theta0, pri, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_ms_abun_nuts`, spec, theta0, pri, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_ms_count_nuts_joint_logpost <- function(spec, theta, pri, sigma_beta, sigma_logr) {
    .Call(`_tulpaObs_cpp_ms_count_nuts_joint_logpost`, spec, theta, pri, sigma_beta, sigma_logr)
}

cpp_ms_count_nuts <- function(spec, theta0, pri, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_ms_count_nuts`, spec, theta0, pri, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_ms_dyn_occu_nuts_joint_logpost <- function(spec, theta, pri, sigma_beta) {
    .Call(`_tulpaObs_cpp_ms_dyn_occu_nuts_joint_logpost`, spec, theta, pri, sigma_beta)
}

cpp_ms_dyn_occu_nuts <- function(spec, theta0, pri, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_ms_dyn_occu_nuts`, spec, theta0, pri, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_ms_int_occu_nuts_joint_logpost <- function(spec, theta, pri, sigma_beta) {
    .Call(`_tulpaObs_cpp_ms_int_occu_nuts_joint_logpost`, spec, theta, pri, sigma_beta)
}

cpp_ms_int_occu_nuts <- function(spec, theta0, pri, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_ms_int_occu_nuts`, spec, theta0, pri, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_ms_nmix_ploglik_batch <- function(y, species_idx, site_idx, X_p, X_lambda, draws, mu_off, b_off, chol_lam_off, chol_p_off, chol_logr_off, p_lam, p_p, n_species, n_sites, is_nb, K_max, n_threads) {
    .Call(`_tulpaObs_cpp_ms_nmix_ploglik_batch`, y, species_idx, site_idx, X_p, X_lambda, draws, mu_off, b_off, chol_lam_off, chol_p_off, chol_logr_off, p_lam, p_p, n_species, n_sites, is_nb, K_max, n_threads)
}

cpp_ms_occu_cover_nuts_joint_logpost <- function(spec, theta, pri, sigma_beta) {
    .Call(`_tulpaObs_cpp_ms_occu_cover_nuts_joint_logpost`, spec, theta, pri, sigma_beta)
}

cpp_ms_occu_cover_nuts <- function(spec, theta0, pri, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_ms_occu_cover_nuts`, spec, theta0, pri, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_ms_ocs_marginal_grad <- function(spec, theta_inner) {
    .Call(`_tulpaObs_cpp_ms_ocs_marginal_grad`, spec, theta_inner)
}

cpp_ms_ocs_marginal_ll <- function(spec, theta_inner) {
    .Call(`_tulpaObs_cpp_ms_ocs_marginal_ll`, spec, theta_inner)
}

cpp_ms_ocs_joint_logpost <- function(spec, theta, pri, sigma_beta, sd_L, constrain = FALSE) {
    .Call(`_tulpaObs_cpp_ms_ocs_joint_logpost`, spec, theta, pri, sigma_beta, sd_L, constrain)
}

cpp_ms_ocs_nuts <- function(spec, theta0, pri, sigma_beta, sd_L, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose, constrain = FALSE) {
    .Call(`_tulpaObs_cpp_ms_ocs_nuts`, spec, theta0, pri, sigma_beta, sd_L, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose, constrain)
}

cpp_ms_occu_nuts_joint_logpost <- function(spec, theta, pri, sigma_beta) {
    .Call(`_tulpaObs_cpp_ms_occu_nuts_joint_logpost`, spec, theta, pri, sigma_beta)
}

cpp_ms_occu_nuts <- function(spec, theta0, pri, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_ms_occu_nuts`, spec, theta0, pri, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_ms_occu_site_cell <- function(eta_psi, eta_p, n_valid, n_det, observed) {
    .Call(`_tulpaObs_cpp_ms_occu_site_cell`, eta_psi, eta_p, n_valid, n_det, observed)
}

cpp_ms_occu_spatial_icar <- function(X_psi, X_p, n_valid, n_det, map_site_to_unit, n_spatial, adj_row_ptr, adj_col_idx, n_neighbors, tau_grid, mu_init, Sigma_psi_init, Sigma_p_init, max_iter_em, verbose) {
    .Call(`_tulpaObs_cpp_ms_occu_spatial_icar`, X_psi, X_p, n_valid, n_det, map_site_to_unit, n_spatial, adj_row_ptr, adj_col_idx, n_neighbors, tau_grid, mu_init, Sigma_psi_init, Sigma_p_init, max_iter_em, verbose)
}

cpp_ms_occu_spatial_car_proper <- function(X_psi, X_p, n_valid, n_det, map_site_to_unit, n_spatial, adj_row_ptr, adj_col_idx, n_neighbors, tau_grid, rho_grid, log_det_Q_rho, mu_init, Sigma_psi_init, Sigma_p_init, max_iter_em, verbose) {
    .Call(`_tulpaObs_cpp_ms_occu_spatial_car_proper`, X_psi, X_p, n_valid, n_det, map_site_to_unit, n_spatial, adj_row_ptr, adj_col_idx, n_neighbors, tau_grid, rho_grid, log_det_Q_rho, mu_init, Sigma_psi_init, Sigma_p_init, max_iter_em, verbose)
}

cpp_ms_occu_spatial_bym2 <- function(X_psi, X_p, n_valid, n_det, map_site_to_unit, n_spatial, adj_row_ptr, adj_col_idx, n_neighbors, sigma_grid, rho_grid, scale_factor, mu_init, Sigma_psi_init, Sigma_p_init, max_iter_em, verbose) {
    .Call(`_tulpaObs_cpp_ms_occu_spatial_bym2`, X_psi, X_p, n_valid, n_det, map_site_to_unit, n_spatial, adj_row_ptr, adj_col_idx, n_neighbors, sigma_grid, rho_grid, scale_factor, mu_init, Sigma_psi_init, Sigma_p_init, max_iter_em, verbose)
}

cpp_ms_ocs_ploglik <- function(draws, X_occ, X_det_site, X_det_visit, X_pos_site, X_pos_visit, y, y_pos, valid, N, J, S, K, P_occ, P_p, P_pos, P_p_site, P_pos_site, cover_factor, is_beta, n_threads) {
    .Call(`_tulpaObs_cpp_ms_ocs_ploglik`, draws, X_occ, X_det_site, X_det_visit, X_pos_site, X_pos_visit, y, y_pos, valid, N, J, S, K, P_occ, P_p, P_pos, P_p_site, P_pos_site, cover_factor, is_beta, n_threads)
}

cpp_nmix_community_em <- function(oracle, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter = 100L, tol = 1e-6, inner_max = 50L, inner_tol = 1e-8, sigma_beta = 100.0, verbose = FALSE) {
    .Call(`_tulpaObs_cpp_nmix_community_em`, oracle, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter, tol, inner_max, inner_tol, sigma_beta, verbose)
}

cpp_nmix_community_field_solve <- function(y, site_idx, species_idx, X_lambda, X_p, coef_lambda, coef_p, map_site_to_unit_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau, rho, log_det_Q_rho, z_init, K_max, max_iter = 100L, tol = 1e-6, verbose = FALSE) {
    .Call(`_tulpaObs_cpp_nmix_community_field_solve`, y, site_idx, species_idx, X_lambda, X_p, coef_lambda, coef_p, map_site_to_unit_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau, rho, log_det_Q_rho, z_init, K_max, max_iter, tol, verbose)
}

cpp_nmix_community_oracle <- function(y, site_idx, species_idx, X_lambda, X_p, n_sites, n_species, K_max, nb = FALSE, zi = FALSE, headroom = -1L) {
    .Call(`_tulpaObs_cpp_nmix_community_oracle`, y, site_idx, species_idx, X_lambda, X_p, n_sites, n_species, K_max, nb, zi, headroom)
}

cpp_nmix_community_spatial_icar <- function(oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em = 100L, tol_em = 1e-4, inner_max = 50L, inner_tol = 1e-6, sigma_beta = 100.0, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nmix_community_spatial_icar`, oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nmix_community_spatial_car_proper <- function(oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, log_det_Q_rho, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em = 100L, tol_em = 1e-4, inner_max = 50L, inner_tol = 1e-6, sigma_beta = 100.0, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nmix_community_spatial_car_proper`, oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, log_det_Q_rho, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nmix_community_spatial_bym2 <- function(oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, scale_factor, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em = 100L, tol_em = 1e-4, inner_max = 50L, inner_tol = 1e-6, sigma_beta = 100.0, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nmix_community_spatial_bym2`, oracle, map_site_to_unit_R, X_lambda_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, scale_factor, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nmix_community_spatial_spde <- function(oracle, X_lambda_R, A_R, Q_list, log_det_Q, theta_grid_R, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em = 100L, tol_em = 1e-4, inner_max = 50L, inner_tol = 1e-6, sigma_beta = 100.0, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nmix_community_spatial_spde`, oracle, X_lambda_R, A_R, Q_list, log_det_Q, theta_grid_R, r_grid, mu_init, Sigma_lambda_init, Sigma_p_init, max_iter_em, tol_em, inner_max, inner_tol, sigma_beta, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nmix_spatial_community_oracle <- function(y, site_idx, species_idx, X_lambda, X_p, n_sites, n_species, K_max) {
    .Call(`_tulpaObs_cpp_nmix_spatial_community_oracle`, y, site_idx, species_idx, X_lambda, X_p, n_sites, n_species, K_max)
}

cpp_nmix_spatial_community_set_offset <- function(oracle_ptr, z) {
    invisible(.Call(`_tulpaObs_cpp_nmix_spatial_community_set_offset`, oracle_ptr, z))
}

cpp_nmix_laplace_fixed <- function(y, site_idx, X_lambda_R, X_p_R, beta_lambda_init, beta_p_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max, headroom = -1L) {
    .Call(`_tulpaObs_cpp_nmix_laplace_fixed`, y, site_idx, X_lambda_R, X_p_R, beta_lambda_init, beta_p_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max, headroom)
}

cpp_nmix_total_log_lik <- function(y, site_idx, eta_p, eta_lambda, K_max, r, headroom = -1L) {
    .Call(`_tulpaObs_cpp_nmix_total_log_lik`, y, site_idx, eta_p, eta_lambda, K_max, r, headroom)
}

cpp_nmix_ploglik_batch <- function(y, site_idx, eta_p, eta_lambda, K_max, r_vec, n_threads) {
    .Call(`_tulpaObs_cpp_nmix_ploglik_batch`, y, site_idx, eta_p, eta_lambda, K_max, r_vec, n_threads)
}

cpp_removal_ploglik_batch <- function(y, site_idx, eta_p, eta_lambda, K_max, r_vec, n_threads) {
    .Call(`_tulpaObs_cpp_removal_ploglik_batch`, y, site_idx, eta_p, eta_lambda, K_max, r_vec, n_threads)
}

cpp_fp_occu_ploglik_batch <- function(y, site_idx, eta_psi, eta_p11, eta_p10, eta_b, n_threads) {
    .Call(`_tulpaObs_cpp_fp_occu_ploglik_batch`, y, site_idx, eta_psi, eta_p11, eta_p10, eta_b, n_threads)
}

cpp_nmix_grouped_oracle <- function(arm, y, site_idx, X_lambda, X_p, Z_site, site_group, n_sites, n_groups, K_max, nb = FALSE, headroom = -1L) {
    .Call(`_tulpaObs_cpp_nmix_grouped_oracle`, arm, y, site_idx, X_lambda, X_p, Z_site, site_group, n_sites, n_groups, K_max, nb, headroom)
}

cpp_nested_laplace_nmix_icar <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, beta_lambda_init, beta_p_init, z_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_nmix_icar`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, beta_lambda_init, beta_p_init, z_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nested_laplace_nmix_car_proper <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, r_grid, beta_lambda_init, beta_p_init, z_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_nmix_car_proper`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, r_grid, beta_lambda_init, beta_p_init, z_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nested_laplace_nmix_bym2 <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, r_grid, scale_factor, beta_lambda_init, beta_p_init, v_init = NULL, w_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_nmix_bym2`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, r_grid, scale_factor, beta_lambda_init, beta_p_init, v_init, w_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nested_laplace_nmix_spde <- function(y, site_idx, X_lambda_R, X_p_R, A_R, Q_list, log_det_Q, theta_grid_R, r_grid, beta_lambda_init, beta_p_init, u_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_nmix_spde`, y, site_idx, X_lambda_R, X_p_R, A_R, Q_list, log_det_Q, theta_grid_R, r_grid, beta_lambda_init, beta_p_init, u_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

occ_make_nested_likelihood <- function(y, det_prob) {
    .Call(`_tulpaObs_occ_make_nested_likelihood`, y, det_prob)
}

cpp_occu_cover_cdf_limits <- function(X_occ, X_det_site, X_det_visit, b_occ, b_det, field_occ, valid, any_det, n_threads) {
    .Call(`_tulpaObs_cpp_occu_cover_cdf_limits`, X_occ, X_det_site, X_det_visit, b_occ, b_det, field_occ, valid, any_det, n_threads)
}

cpp_occu_cover_ppc <- function(psi_all, p_all, ep_all, y, y_pos, valid, any_det, n_valid, disp, positive, freeman) {
    .Call(`_tulpaObs_cpp_occu_cover_ppc`, psi_all, p_all, ep_all, y, y_pos, valid, any_det, n_valid, disp, positive, freeman)
}

cpp_occu_cover_ppc_agg <- function(psi_all, p_all, ep_all, y, valid, any_det, n_valid, disp, mode_code, pos_site, yv, vals_flat, unit_off, disp2, positive, freeman) {
    .Call(`_tulpaObs_cpp_occu_cover_ppc_agg`, psi_all, p_all, ep_all, y, valid, any_det, n_valid, disp, mode_code, pos_site, yv, vals_flat, unit_off, disp2, positive, freeman)
}

cpp_occu_cover_nuts_joint_logpost <- function(spec, theta, sigma_beta, sigma_logdisp) {
    .Call(`_tulpaObs_cpp_occu_cover_nuts_joint_logpost`, spec, theta, sigma_beta, sigma_logdisp)
}

cpp_occu_cover_nuts <- function(spec, theta0, sigma_beta, sigma_logdisp, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_occu_cover_nuts`, spec, theta0, sigma_beta, sigma_logdisp, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_occu_cover_ploglik_ragged <- function(X_occ, X_det_site, X_pos_site, X_det_visit, X_pos_visit, site_of_visit, y_det_visit, y_pos_visit, b_occ, b_det, b_pos, disp, field_occ, field_pos, positive, eta_bound, n_threads) {
    .Call(`_tulpaObs_cpp_occu_cover_ploglik_ragged`, X_occ, X_det_site, X_pos_site, X_det_visit, X_pos_visit, site_of_visit, y_det_visit, y_pos_visit, b_occ, b_det, b_pos, disp, field_occ, field_pos, positive, eta_bound, n_threads)
}

cpp_occu_single_ploglik <- function(eta_psi, eta_p, y, n_threads) {
    .Call(`_tulpaObs_cpp_occu_single_ploglik`, eta_psi, eta_p, y, n_threads)
}

cpp_occu_dynamic_ploglik <- function(eta_psi1, eta_p, eta_gam, eta_eps, y, n_visits, any_detected, n_sites, max_visits, n_seasons, n_threads) {
    .Call(`_tulpaObs_cpp_occu_dynamic_ploglik`, eta_psi1, eta_p, eta_gam, eta_eps, y, n_visits, any_detected, n_sites, max_visits, n_seasons, n_threads)
}

cpp_occu_integrated_ploglik <- function(eta_psi, eta_src, K1, K0, n_sources, n_threads) {
    .Call(`_tulpaObs_cpp_occu_integrated_ploglik`, eta_psi, eta_src, K1, K0, n_sources, n_threads)
}

cpp_occu_fit <- function(spec_r) {
    .Call(`_tulpaObs_cpp_occu_fit`, spec_r)
}

cpp_occu_ms_cover_ploglik <- function(draws, X_psi, X_theta, X_p_site, X_p_visit, X_pos_site, X_pos_visit, y, y_pos, valid, plot_cell, positive, idx_psi, p_psi, idx_theta, p_theta, idx_p_site, p_p_site, idx_p_visit, p_p_visit, idx_pos_site, p_pos_site, idx_pos_visit, p_pos_visit, idx_disp, n_threads) {
    .Call(`_tulpaObs_cpp_occu_ms_cover_ploglik`, draws, X_psi, X_theta, X_p_site, X_p_visit, X_pos_site, X_pos_visit, y, y_pos, valid, plot_cell, positive, idx_psi, p_psi, idx_theta, p_theta, idx_p_site, p_p_site, idx_p_visit, p_p_visit, idx_pos_site, p_pos_site, idx_pos_visit, p_pos_visit, idx_disp, n_threads)
}

cpp_occu_ms_cover_nuts_joint_logpost <- function(spec, theta, sigma_beta) {
    .Call(`_tulpaObs_cpp_occu_ms_cover_nuts_joint_logpost`, spec, theta, sigma_beta)
}

cpp_occu_ms_cover_nuts <- function(spec, theta0, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_occu_ms_cover_nuts`, spec, theta0, sigma_beta, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_removal_laplace_fixed <- function(y, site_idx, X_lambda_R, X_p_R, beta_lambda_init, beta_p_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max) {
    .Call(`_tulpaObs_cpp_removal_laplace_fixed`, y, site_idx, X_lambda_R, X_p_R, beta_lambda_init, beta_p_init, K_max, max_iter, tol, verbose, nb, log_r_init, theta_max)
}

cpp_removal_total_log_lik <- function(y, site_idx, eta_p, eta_lambda, K_max, r) {
    .Call(`_tulpaObs_cpp_removal_total_log_lik`, y, site_idx, eta_p, eta_lambda, K_max, r)
}

cpp_removal_nuts_joint_logpost <- function(spec, theta, sigma_beta, sigma_logr) {
    .Call(`_tulpaObs_cpp_removal_nuts_joint_logpost`, spec, theta, sigma_beta, sigma_logr)
}

cpp_removal_nuts <- function(spec, theta0, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose) {
    .Call(`_tulpaObs_cpp_removal_nuts`, spec, theta0, sigma_beta, sigma_logr, inv_metric, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

cpp_removal_grouped_oracle <- function(arm, y, site_idx, X_lambda, X_p, Z_site, site_group, n_sites, n_groups, K_max, nb = FALSE) {
    .Call(`_tulpaObs_cpp_removal_grouped_oracle`, arm, y, site_idx, X_lambda, X_p, Z_site, site_group, n_sites, n_groups, K_max, nb)
}

cpp_nested_laplace_removal_icar <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, beta_lambda_init, beta_p_init, z_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_removal_icar`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, r_grid, beta_lambda_init, beta_p_init, z_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nested_laplace_removal_bym2 <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, r_grid, scale_factor, beta_lambda_init, beta_p_init, v_init = NULL, w_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_removal_bym2`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, sigma_grid, rho_grid, r_grid, scale_factor, beta_lambda_init, beta_p_init, v_init, w_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_nested_laplace_removal_car_proper <- function(y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, r_grid, beta_lambda_init, beta_p_init, z_init = NULL, K_max = -1L, max_iter = 100L, tol = 1e-6, verbose = FALSE, progress = FALSE, progress_every = 0L, progress_throttle = 0.0, progress_file = "") {
    .Call(`_tulpaObs_cpp_nested_laplace_removal_car_proper`, y, site_idx, map_site_to_unit_R, X_lambda_R, X_p_R, adj_row_ptr, adj_col_idx, n_neighbors, n_spatial, tau_grid, rho_grid, r_grid, beta_lambda_init, beta_p_init, z_init, K_max, max_iter, tol, verbose, progress, progress_every, progress_throttle, progress_file)
}

cpp_simulate_nmix <- function(X_lambda, X_p, draws, site_idx, visit_idx, n_sites, max_visits, p_lam, p_p, is_nb, r_size, nsim, zi_omega = NA_real_) {
    .Call(`_tulpaObs_cpp_simulate_nmix`, X_lambda, X_p, draws, site_idx, visit_idx, n_sites, max_visits, p_lam, p_p, is_nb, r_size, nsim, zi_omega)
}

cpp_simulate_removal <- function(X_lambda, X_p, draws, site_idx, visit_idx, n_sites, n_pass, p_lam, p_p, is_nb, r_size, nsim) {
    .Call(`_tulpaObs_cpp_simulate_removal`, X_lambda, X_p, draws, site_idx, visit_idx, n_sites, n_pass, p_lam, p_p, is_nb, r_size, nsim)
}

cpp_simulate_dyn_abun <- function(X_lambda, X_p, X_omega, X_gamma, draws, n_sites, T, J, p_lam, p_p, p_om, p_gm, is_nb, r_disp, nsim) {
    .Call(`_tulpaObs_cpp_simulate_dyn_abun`, X_lambda, X_p, X_omega, X_gamma, draws, n_sites, T, J, p_lam, p_p, p_om, p_gm, is_nb, r_disp, nsim)
}

cpp_simulate_fp_occu <- function(X_psi, X_p11, X_p10, X_b, draws, n_sites, J, p_psi, p_p11, p_p10, p_b, nsim) {
    .Call(`_tulpaObs_cpp_simulate_fp_occu`, X_psi, X_p11, X_p10, X_b, draws, n_sites, J, p_psi, p_p11, p_p10, p_b, nsim)
}

cpp_simulate_distance <- function(X_lambda, X_sigma, draws, cutpoints, key, transect, b_shape, n_sites, n_bins, p_lam, p_sig, is_nb, r_size, nsim) {
    .Call(`_tulpaObs_cpp_simulate_distance`, X_lambda, X_sigma, draws, cutpoints, key, transect, b_shape, n_sites, n_bins, p_lam, p_sig, is_nb, r_size, nsim)
}

cpp_simulate_ms_nmix <- function(lambda, p, size_s, obs_mask, n_sites, max_v, n_species, nsim) {
    .Call(`_tulpaObs_cpp_simulate_ms_nmix`, lambda, p, size_s, obs_mask, n_sites, max_v, n_species, nsim)
}

cpp_simulate_ms_occu <- function(psi, p, valid, n_sites, max_v, n_species, nsim) {
    .Call(`_tulpaObs_cpp_simulate_ms_occu`, psi, p, valid, n_sites, max_v, n_species, nsim)
}

cpp_simulate_ms_occu_cover <- function(psi, p_mat, ep_mat, valid, disp, positive, n_sites, max_v, n_species, nsim) {
    .Call(`_tulpaObs_cpp_simulate_ms_occu_cover`, psi, p_mat, ep_mat, valid, disp, positive, n_sites, max_v, n_species, nsim)
}

cpp_simulate_ms_dyn_occu <- function(psi1, p, gamma, eps, valid, n_sites, max_v, n_seasons, n_species, nsim) {
    .Call(`_tulpaObs_cpp_simulate_ms_dyn_occu`, psi1, p, gamma, eps, valid, n_sites, max_v, n_seasons, n_species, nsim)
}

cpp_simulate_ms_int_occu <- function(psi, pd, valid, J_d, n_sites, n_species, D, nsim) {
    .Call(`_tulpaObs_cpp_simulate_ms_int_occu`, psi, pd, valid, J_d, n_sites, n_species, D, nsim)
}

cpp_simulate_single <- function(X_occ, X_det, draws, y, p_occ, p_det, nsim) {
    .Call(`_tulpaObs_cpp_simulate_single`, X_occ, X_det, draws, y, p_occ, p_det, nsim)
}

cpp_single_ppc <- function(X_occ, X_det, draws, draw_idx, y, n_valid, any_det, freeman) {
    .Call(`_tulpaObs_cpp_single_ppc`, X_occ, X_det, draws, draw_idx, y, n_valid, any_det, freeman)
}

cpp_single_pit <- function(X_occ, X_det, draws, draw_idx, y) {
    .Call(`_tulpaObs_cpp_single_pit`, X_occ, X_det, draws, draw_idx, y)
}

